### ISSUE TITLE
"type" missing when uniform distribution number provider is used (Predicate generator)

### ISSUE THREAD

**Issue by Zsigio** [misode/minecraft-schemas#24]
The "type" tag for the number provider doesn't show up in the output JSON when a uniform distribution is used in the predicate generator. This breaks the predicate file. (tested in 20w51a)

### Recreation

1. Open predicate generator
2. Set condition to value check
3. Set first number provider to uniform

### Expected result

`{ "condition": "minecraft:value_check", "value": { "type": "minecraft:uniform", "min": 0, "max": 0 }, "range": { "min": 0, "max": 0 } }`

### What I get instead

`{ "condition": "minecraft:value_check", "value": { "min": 0, "max": 0 }, "range": { "min": 0, "max": 0 } }`

**Comment by SPGoding** [comment]
This is a bug of Minecraft tracked at [MC-206118](https://bugs.mojang.com/browse/MC-206118).

**Comment by misode** [comment]
@Zsigio In the meantime, select `Uniform+` in the dropdown.

**Comment by Zsigio** [comment]
Alright, thank you, we'll see if mojang decides to fix it or not then. Uniform+ is a great temporary solution.

**Comment by Zsigio** [comment]
For future reference, the bug got fixed by Mojang in 21w03a
