### ISSUE TITLE
Machine User Replaced My File

### ISSUE THREAD

**Issue by champsing** [misode/minecraft-schemas#35]
It is very appreciated that the developers implemented my translation json file! 
But it seems like the machine user of Weblate, SPWeblate, had replaced my file with the old one. 
The reason may be that the robot didn't know that those strings were translated, so it deleted them.
These are screenshots of the workflow. I will be very grateful if you could inform the robot of my new translation!
![history](https://user-images.githubusercontent.com/88385811/128503081-22530694-7e3b-48f3-aa59-0f4d1466b2b2.png)
![bot](https://user-images.githubusercontent.com/88385811/128503091-0798a6a4-9487-466a-b37d-d14e27425f5a.png)

**Comment by SPGoding** [comment]
The bot removes all keys that don't exist in `en_us.json`. I've disabled that feature for this repo for now. Thanks a lot!
