### ISSUE TITLE
loot_table bonus_roll and rolls do not accept negative values

### ISSUE THREAD

**Issue by ChenCMD** [misode/minecraft-schemas#4]

**Comment by misode** [comment]
Does the game accept negative values and do those provide valuable results?

**Comment by ChenCMD** [comment]
Yes.  For example, if you enter a negative value for rolls and set bonus_roll to 1, `rolls + luck * bonus_roll` will be the number of items drawn.

**Comment by ChenCMD** [comment]
Yes.  For example, if you enter a negative value for rolls and set bonus_roll to 1, `rolls - luck * bonus_roll` will be the number of items drawn.

**Comment by ChenCMD** [comment]
Yes.  For example, if you enter a negative value for rolls and set bonus_roll to 1, `rolls - luck * bonus_roll` will be the number of items drawn.

**Comment by ChenCMD** [comment]
Yes.  For example, if you enter a negative value for rolls and set bonus_roll to 1, `rolls - luck * bonus_roll` will be the number of items drawn.

**Comment by ChenCMD** [comment]
Yes.  For example, if you enter a negative value for rolls and set bonus_roll to 1, `rolls - luck * bonus_roll` will be the number of items drawn.
