### ISSUE TITLE
Recipe groups for Vanilla blocks

### ISSUE THREAD

**Issue by mainrs** [misode/minecraft-schemas#9]
This would allow tooling such as https://github.com/SPGoding/datapack-language-server to autocomplete the group field as well.

**Comment by SPGoding** [comment]
From what I understand, you could put anything in `group`, so I'm not sure what you'd like DHP to autocomplete :thinking:

**Comment by mainrs** [comment]
That's correct, but Vanilla does define a bunch of them already (like `sticks` for example). I thought to get autocomplete for those would be nice to have.

**Comment by misode** [comment]
Maybe DHP could treat this like an unnamespaced dynamic registry? Either way adding the vanilla groups as suggestions seems like a good idea.

**Comment by SPGoding** [comment]
Created SPGoding/datapack-language-server#729 to track this, so I guess this ticket could be closed ;D
